version: '3.7'
services:  
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'discovery.type=single-node'
    volumes: 
     - 'esdata1:/usr/share/elasticsearch/data'
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    ports:
      - "5601:5601"
    depends_on: 
      - elasticsearch
    environment: 
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'     
        
volumes:
  esdata1:
    driver: local
